---
#
# Ansible managed
#
repository:
  description: Enable or disable automatic starting of servers upon installation of packages.
  homepage: https://robertdebock.nl/
  topics: aptautostart, apt, autostart, service, invokerc, sysvinit, systemctl, hacktoberfest
