---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="debian" tag="stable"
    - image="debian" tag="unstable"
    - image="debian"
    - image="ubuntu" tag="rolling"
    - image="ubuntu" tag="devel"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="debian" tag="unstable"
    - env: image="ubuntu" tag="rolling"
    - env: image="ubuntu" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "Svem6sqjeugrAOKoN2CJcXekY9HKgiwgqR9Wu0AmLNQRTa1RQhkmerVVa9SXbtm+a8NODDjnU9dEitY2CDfOs2sHwMwWh0XNnXM4LlIgmdV6yWSeESn/mIpxt7FddJHufIJQ98yGobjQ3r8j4MuF4//4CYA75n671KApsNraTMGmN9Irwij8CAMhGwbadobUaIZuYNnPlPhinEmMzgXhUYMgWFBE30oemDjQoosceAuhUw70Bois/9ocVZT23Sx0RnsIUsHio8/wWn1jdmbEvjcr2XG12Qu3WMtlnS9o30YF0zpvArvEkCrCyjQ/RBRzxt8agaMLopHKTN1LC1AfQYUhZBy5kvPDeym2soYeYhIzie60z9uVxZLV0+cWOUUjL6v0+af8DsQqzIHAes9etoVpwWyPsDiEp8LLk/NkInsRH7q6STDtfkjGJjt/KBPb5pMepDkIZD+MRSkOW4tHUnNHwoNcw+66uyjbi3auMkx5lm5ReQkhgbmHl1SNtMXqmYw8+bdHbPjB1AwcwsryN3bWBDFqCImyq3OjkuE+l7NasQSxVn/BxH2cXVUY93nr7Av/0BQCKBAoPYcW1UBGQQ7jU35947OaFZaWWOlEK+xpu/JmWzeb/Rl/IcQtKBLDFpLK/zGtDpjaJp+iAtlqeS+hOVr3NZVi5d0GSE9JIhk="
  email: false
