---
# tasks file for apt_autostart

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: manage automatic service management
  block:
    - name: disable automatic service management on installation
      copy:
        dest: /usr/sbin/policy-rc.d
        content: "exit 101"
        mode: "755"
      when:
        - apt_autostart_state == "disabled"

    - name: enable automatic service management on installation
      file:
        path: /usr/sbin/policy-rc.d
        state: absent
      when:
        - apt_autostart_state == "enabled"
  when:
    - ansible_pkg_mgr == "apt"
